### ISSUE TITLE
Transports

### ISSUE THREAD

**Issue by larshp** [EduardoCopat/code-review-with-abapgit#1]
Hi Eduardo,
Cool stuff

Note that abapGit works on R3TR level not LIMU. I.e. 2 methods in a class can be in 2 different transports, however in abapGit it is the same object.

**Comment by eduardocopat** [comment]
@larshp Hi, Lars, thanks for taking a look :). It's not finished yet, it's just a sketch/an idea. Also, some images were failing and now they are okay.

I still think most of this could be automated, for there are BADIs and abapGit APIs to do so...

I will add that to the slides.
